/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qgg_ndkdemo_NdkUtil */

#ifndef _Included_com_qgg_ndkdemo_NdkUtil
#define _Included_com_qgg_ndkdemo_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qgg_ndkdemo_NdkUtil
 * Method:    ndkHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qgg_ndkdemo_NdkUtil_ndkHelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
